apiVersion: v1
kind: Service
metadata:
  name: llama-server
  namespace: ai
spec:
  type: LoadBalancer
  selector:
    app: llama-server
  ports:
    - name: http
      port: 8000
      targetPort: 8000

