apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-path
  namespace: flux-system
spec:
  interval: 1m
  path: ./infrastructure/local-path
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
